baseURL: 'https://ryanjennin.gs/'
languageCode: en-us
title: ryan jennings
publishDir: public
buildDrafts: false
googleAnalytics: UA-28532156-1
paginate: 10
footnotereturnlinkcontents: ↩
theme: coda
permalinks:
  post: '/:year/:month/:day/:slug'
params:
  author: Ryan Jennings
  description: 'a cog in the machine, functioning and meaningless'
  subdescription: 'ramblings of an engineer, musician and madman'
  introURL: /post
  githubUsername: ryjen
  copyright: '&copy; all rights reserved, ryan jennings'
  highlight: true
  highlightStyle: solarized
  brandName: ryan jennings
menu:
  main:
    - name: verbage
      identifier: verbage
      pre: newspaper
      weight: 1
      url: "/verbage"
    - name: art
      identifier: art
      pre: icons
      weight: 2
      url: "/art"
    - name: things
      identifier: things
      pre: object-ungroup
      weight: 3
      url: "/things"
      # verbage items 
    - name: blog
      identifier: blog
      pre: rss
      weight: 1
      url: /post
      parent: verbage 
    - name: musings
      identifier: musings
      pre: comment-dots
      weight: 2
      url: /musings
      parent: verbage
# art items
    - name: music
      identifier: name
      pre: music
      weight: 1
      url: /music
      parent: art
    - name: doodles
      identifier: doodles
      pre: image
      description: "various drawings, sketches and watercolors"
      weight: 2
      url: /doodles
      parent: art
    - name: poems
      identifier: poems
      pre: pen-nib
      description: "various poems expressed"
      weight: 3
      url: /post/poems
      parent: art
      # thing items
    - name: books
      identifier: books
      pre: book
      weight: 1
      url: /things/books
      parent: things
    - name: tech
      identifier: tech
      pre: robot
      weight: 2
      url: /things/tech
      parent: things
  icons:
    - url: 'https://github.com/ryjen'
      name: fab fa-github
      weight: 4
    - url: 'https://linkedin.com/in/ryjen'
      name: fab fa-linkedin
      weight: 5
    - url: 'https://micrantha.com'
      name: fas fa-building
      weight: 3
    - url: 'mailto:robert@ryanjennin.gs'
      name: fas fa-envelope
      type: fas
      weight: 2

