#!/bin/sh

rsync=$(which rsync)

if [ -z "$rsync" ]; then
    echo "rysync not available";
    exit 1;
fi

rm -rf ./deploy/public/*
$rsync -rtvu --delete --exclude=.git* ./public/ ./deploy/public/

exit 0;
